server:
  port: 8888

spring:
  application:
    name: game
  datasource:
    druid:
      driver-class-name: cm.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 5
      min-idle: 5
      max-wait: 60000
      max-active: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat
      max-open-prepared-statements: 20
      pool-prepared-statements: true
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      validation-query: select 'x'
    username: root
    password: 123456
    jdbc-url: jdbc:mysql://127.0.0.1:3306/redis_test
  redis:
    database: 0
    host: 192.168.174.129
    port: 6379
    pool:
      max-active: 500
      max-idle: 8
      min-idle: 0
      max-wait: -1
    timeout:
